##端口号
server:
  port: 8808


spring:
  application:
    name: wx-huaishangtong

  # --- datasource
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/huaian?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
#    username: root
#    password: 1234

    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.220.161:1521:ha_hst
    username: ha_hst
    password: ha_hst1qaz

  # --- redis
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456  # Redis服务器连接密码（默认为空）

    jedis:
      pool:
        max-idle: 8  # 连接池中的最大空闲连接（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0   # 连接池中的最小空闲连接
        max-active: 8 # 最大连接数
    timeout: 300

logging:
  level:
    com.huaian.portablecode: debug
    com.huaian.portablecode.mapper: debug
  file:
    name: log\process.log


# -- appId
app:
  url: https://api.weixin.qq.com/sns/jscode2session
  app-id: wxdafb5287ee16ff37
  secret-key: e1ef395832373d1560c59f07bc3b354e